name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      
      - name: Setup WASM BUILD
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Install WASM
        run: npm run build-wasm

      - name: Install Dependencies
        run: npm i

      - name: Copy env
        run: cd src/config && cp config.example.ts config.ts

      - name: Run Build
        run: npm run build
